### ISSUE TITLE
Offline plate-solve button is disabled

### ISSUE THREAD

**Issue by QK-sampson** [ThemosTsikas/PhotoPolarAlign#9]
Hello ThemosTsikas,
I tried to install PPA on my Raspberry pi3. Astrometry was installed on my raspri and it could make offline plate solve using shell 'solve-field' but the Local plate solve is not enable and dimmed. How can I enable the button for local plate solve.
Thanks !!

**Comment by ThemosTsikas** [comment]
Hello,

I make sure that my PATH contains the directory where solve-field is installed (/usr/local/astrometry/bin in my case) before I issue  "python2.7 PPA.py" in a shell. I also have these in my PPA.ini

```
[local]
shell = /bin/bash -c "%s"
downscale = 2
configfile = /usr/local/astrometry/etc/astrometry4100.cfg
scale_units = arcsecperpix
scale_low = 1.0
scale_hi = 120.0
xtra = -B none -P none -M none -N none -S none -R none -U none -p

```

**Comment by QK-sampson** [comment]
Thank you for your kindness !
This is my PPA.ini on my Raspberry pi3 but the local button does not work. >_< 

[local]
shell = /usr/bin/solve-field
downscale = 2
configfile = /etc/astrometry.cfg
scale_units = arcsecperpix
scale_low = 2.0
scale_hi = 8.0
xtra =

**Comment by ThemosTsikas** [comment]
Well, you have to change your shell variable in PPA.ini to be exactly what I had

`shell = /bin/bash -c "%s"`

unless your bash shell is installed somewhere else. And my contents of the solve-field directory look like this 

```
an-fitstopnm*
an-pnmtofits*
astrometry-engine*
build-astrometry-index*
degtohms.py@
downsample-fits*
fits2fits.py@
fits-column-merge*
fitscopy*
fits-flip-endian*
fitsgetext*
fits-guess-scale*
fit-wcs*
get-healpix*
get-wcs*
hmstodeg.py@
hpsplit*
image2pnm.py@
image2xy*
imarith*
imcopy*
imstat*
listhead*
liststruc*
merge-columns.py@
modhead*
new-wcs*
pad-file*
plotann.py@
plot-constellations*
plotquad*
plotstuff*
plotxy*
query-starkd*
removelines.py@
search-index*
solve-field*
subtable*
tablist*
tabmerge*
tabsort*
text2fits.py@
uniformize.py@
votabletofits.py@
wcs-grab*
wcsinfo*
wcs-match*
wcs-pv2sip*
wcs-rd2xy*
wcs-resample*
wcs-to-tan*
wcs-xy2rd*

```

**Comment by QK-sampson** [comment]
Hello ThemosTsikas,
Thank you again for your helping hands! 
The local button is enabled after following your example. But it seems that no "solve-field" is processed after clicking the local button because only "local solve time 0.0018xxxxx" was generated on terminal and no files such as .wcs was generated.

I have checked the installed files for "astrometry.net" synaptic package manager under the ubuntu system and I could find some files that you listed to me under /usr/bin/ (i.e. /usr/bin/solve-field , /usr/bin/fit-wcs)
I don't know what should I do.

I am sorry that I have limited computer knowledge and in fact I don't know python. But I tried hard to learn from internet so that I could 'install' the astro programs on my raspberry pi3.

**Comment by ThemosTsikas** [comment]
Hello, 

could you try running the command as 

OSTYPE=linux python2.7 PPA.py

**Comment by QK-sampson** [comment]
Wow~ It's work now =)
Thank you for your prompt reply! Thank you for your great program and contribution.
Would you mind I share the raspberry pi img that pre-installed PPA to other ? 
I hope I could manage to use PPA when going a remote area. 
You are really nice and helpful ! Thank again !

**Comment by ThemosTsikas** [comment]
Hello, 

Please give it a good workout!  I don't mind what you do with it. I've updated the licence to the most permissive I can find.

**Comment by tiziano0** [comment]
QK-sampson 
Hi I'm interested in testing the PPA on my rasperry armv7.
Did you then set up the .dev? Or do you have an installation procedure?

Thank you

**Comment by ThemosTsikas** [comment]
There is no installation procedure, yet. It should work just like the pi3 did.

**Comment by QK-sampson** [comment]
Hi tiziano0,
I have installed the packages of ujson, astropy, Pillow, numpy, python3-tk, python-scipy, python-pip, python-tk in order to run PPA properly. Also, astrometry.net is needed to install for local plate-solve.

By the way, you could download my Raspberry pi3 image that based on RaspEX distribution and use PPA right away. Download link: https://drive.google.com/open?id=1m_Bm6cnb_5fWJpRF-58xEoRb1FivaJQX

Details of my Raspi image at http://www.hkastroforum.net/viewtopic.php?f=68&t=34371
However, you might need to use google translate for the post in Chinese.

Clear Skies.
Sampson
